# Generated by Django 4.2.8 on 2024-02-18 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_exercisebank_set_workoutexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
